### PR TITLE
Davidc/intent hint

### PR DESCRIPTION
**Pull request by davidcarlisle**
Discussions about intent are still ongoing but it seems a draft based on the issue comment at

https://github.com/w3c/mathml/issues/398#issuecomment-1178880279

Is closer to a final consensus position than the current draft.

I doubt if any wording here is final but I'd propose we merge this to form a new baseline against which people can make comments and new issues.

It would be good to merge this before Thursday's meeting so the gh-pages view is easily seen.

### CODE REVIEW

**Review by NSoiffer — COMMENTED** [review]
There's a lot of text -- any chance you can provide a preview of this branch on your github-pages?

**Comment by davidcarlisle** [comment]
> There's a lot of text -- any chance you can provide a preview of this branch on your github-pages?

@NSoiffer  You can always view locally, but anyway, a few pulls and pushes , and I synced my fork so

https://davidcarlisle.github.io/mathml/#mixing_intent

**Comment by NSoiffer** [comment]
You should add a link for 398 to the start of the section.  I hope we can at least close some of the other discussions/notes.

"Intent Concept Dictionary" -- this is undefined (and the first I've heard of it).

> A literal is intended to correspond to some mathematical concept or operator

I think you mean "concept"

> Note that [intent](https://davidcarlisle.github.io/mathml/#dfn-intent) identifiers are maintained in two lists, currently located at ...

You can drop "Note that", or maybe move the whole paragraph into an issue link or editor's note. 

>In a function [application](https://davidcarlisle.github.io/mathml/#intent_application), if the function is followed by a [hint](https://davidcarlisle.github.io/mathml/#intent_hint) the reading of the name may be suppressed,

missing a comma after "hint" (so actually after the close paren of the link).

I still think munging the examples together with "->" in between is mathematical nonsense, something we have avoided. The complex conjugate is better, but it is still mathematically "silly" (which is a well-defined math term :-)

The audio renditions contain "_"; they should be translated to words ("bar").

The examples of "hint" should be "real" ones:
prefix: !x (as in "not x")
infix: (×) cross-product
postfix: double-factorial
silent:  negative-ion -- Na+  [that really needs renaming]
Not all of these are ideal because putting the name on the operator would do the right thing -- one doesn't need `intent` on a parent `mrow`.

> `<mtr intent="append">`

This probably should be `append@silent`, although I don't think "append" is a great word. Among other things, it is not in the "conceptual dictionary". Using that dictionary, the `mtable` should have "system-of-equations" and the `mtr`s should have "aligned-equation". Being in core, they probably don't need "@silent".

I'm not sure what the appropriate "intent" for the second one is. @dginev?

**Comment by dginev** [comment]
> I'm not sure what the appropriate "intent" for the second one is. @dginev?

This PR is likely not the best place to solve #337 . Or a new issue for "Tabular Intent Core", if you think that would be helpful. As much as I understand the pain of having so much message volume on github, inventing all of this infrastructure requires it.

**Comment by davidcarlisle** [comment]
> > I'm not sure what the appropriate "intent" for the second one is. @dginev?
> 
> This PR is likely not the best place to solve #337 . Or a new issue for "Tabular Intent Core", if you think that would be helpful. As much as I understand the pain of having so much message volume on github, inventing all of this infrastructure requires it.

I'd agree a new issue (or just re-starting that issue) would be better than discussing individual examples here.

But one reason there has been little progress on intent for specific constructs, is failure to tie down a basic syntax, which makes it hard to discuss anything explicit. Which is why I think we need to merge something like this PR sooner rather than later, so the other issues can be discussed using a syntax we can use at least for the first working draft

**Comment by davidcarlisle** [comment]
quoting @NSoiffer 

> You should add a link for 398 to the start of the section. I hope we can at least close some of the other discussions/notes.
> 


**done**  (in the branch, I suppose I'll re-sync the fork later, grmble)

> "Intent Concept Dictionary" -- this is undefined (and the first I've heard of it).
> 

Trying out a new name for "intent lists"  Inspired mostly by Deyan's pushing for clearer separation between NCName being an entry to a known concept and the use as a Literal Name read directly.  "list" sounds like a list of names, "Dictionary" giving an idea of the muliple fields, but open to suggestions on what to call  the things "open" and "Core"

> > A literal is intended to correspond to some mathematical concept or operator
> 
> I think you mean "concept"
> 
Yes probably (That phrase came from an old CG document, I'll adjust)

> > Note that [intent](https://davidcarlisle.github.io/mathml/#dfn-intent) identifiers are maintained in two lists, currently located at ...
> 
> You can drop "Note that", or maybe move the whole paragraph into an issue link or editor's note.
> 

I dropped Note that. This is still calling them "lists" we should do a full sweep over the doc once we decide what to call them. (Perhaps list is OK....)


> > In a function [application](https://davidcarlisle.github.io/mathml/#intent_application), if the function is followed by a [hint](https://davidcarlisle.github.io/mathml/#intent_hint) the reading of the name may be suppressed,
> 
> missing a comma after "hint" (so actually after the close paren of the link).

**done** 
> 
> I still think munging the examples together with "->" in between is mathematical nonsense, something we have avoided. The complex conjugate is better, but it is still mathematically "silly" (which is a well-defined math term :-)
> 

Yes I know. Have I mentioned not agreeing a syntax has been a dis-incentive to generating better examples:-) 

Probably once we have more real examples highlightig specific features: core v open, hints or not, tables, ... Then that block of initial generic examples can go. So I am not too worried about the arrows at this point. (Although I could for now just split it up into multiple examples?)


> The audio renditions contain "_"; they should be translated to words ("bar").
> 
> The examples of "hint" should be "real" ones: prefix: !x (as in "not x") infix: (×) cross-product postfix: double-factorial silent: negative-ion -- Na+ [that really needs renaming] Not all of these are ideal because putting the name on the operator would do the right thing -- one doesn't need `intent` on a parent `mrow`.
> 

Also I wasn't sure if it was clearer to give an example of just the intent or a mathml fragment so

`inner-product @infix ($x,$y)`

or

```
<mrow intent="inner-product @infix ($x,$y)">
  <mi arg="x">A</mi>
  <mi arg="y">B</mi>
</mrow>
```

> > `<mtr intent="append">`
> 
> This probably should be `append@silent`, although I don't think "append" is a great word. Among other things, it is not in the "conceptual dictionary". Using that dictionary, the `mtable` should have "system-of-equations" and the `mtr`s should have "aligned-equation". Being in core, they probably don't need "@silent".

that whole section just comes from some early CG document. If we do specify something for table rows I'd assume it would be core and not need any hint

> 
> I'm not sure what the appropriate "intent" for the second one is. @dginev?

Post merge issues:-)

**Comment by davidcarlisle** [comment]
@NSoiffer  arrow example split up https://davidcarlisle.github.io/mathml/#mixing_intent_examples_notation
cf82849

**Review by brucemiller — APPROVED** [review]
This is a helpful step forward to focus further discussion, refinements and (possibly) retractions.

**Comment by NSoiffer** [comment]
Thanks for the changes. Clearly this is not the final version, so it doesn't have to perfect. My suggestions were just to fix some typos and clarify some things.

**Pull request merged**
