### PR TITLE
Mfenced

### PR DESCRIPTION
**Pull request by NSoiffer**
Tweaked wording of mfenced/mrow equivalence to reminder readers that mfenced is not in core

Removed faked (extra) renderings in the examples.

### CODE REVIEW

**Comment by NSoiffer** [comment]
Hmm -- I'm not sure how @davidcarlisle's changes are in here. I did a rebase before the branch. Could have rebased to gh-pages :-(. I hope this is something easy to fix.

**Comment by davidcarlisle** [comment]
@NSoiffer  may be an issu with the gh action workflow, I wasn't it expcting it to update spec.html in main, I'll check. Doesn't really matter though

**Review by davidcarlisle — COMMENTED** [review]
Looks like this was rebased against gh-pages not main, spec.html should not be in the main branch at all, I have cherry picked the intended commit 53c05169aad866c9c2e2417dde11d3129f8865b4 to presentation.html into main and pushed, so closing this PR

**Comment by davidcarlisle** [comment]
The commit has been cherry picked and added to main and pushed locally, so closing this PR

**Comment by NSoiffer** [comment]
Thanks. I've switched over to main.

**Pull request closed without merging**
