### PR TITLE
folding plan b

### PR DESCRIPTION
**Pull request by davidcarlisle**
Previously folded sections used a html `<details><summary>` CSS-styled to look like a heading at the appropriate level. Unfortunately because the headings have a self-link this resulted in

 ```
<details id="abc"><summary><a href="#abc">§</a> title..</summary>
section here...
</details>
```

And some screen reader configurations could then not separate the open/close interaction on `<summary>`  from  the link interaction on `<a` which is at essentially the same point. And you could get stuck in the link and not open (or close or both depding on exactly the variant used)

This PR uses a form that is simpler to generate and makes a more logically clean DOM tree with a real heading and the open/close interaction moved off the heading. So visually it takes up more space, but OK I think, and is (I hope) usable rather than unusable with chrome+nvda and other combinations.

```
<section>
<h5  id="abc"><a href="#abc">§</a> title..</h5>
<details class="h"><summary class="h"></summary>
section here...
</details>
</section>
```

the real diff is just the first commit changing `indx.html` although I checked in a generated `spec.html` as well here

@ljmaher  hopefully this works

https://davidcarlisle.github.io/mathml/spec.html#presm_mo_linebreaks

----

Not totally related but in the current draft open sections in chapter 3 had no special style but open sections in chapter 4 were boxed (which makes it easier to see were the text ends, but is a bit distracting)

Here I have gone for a middle way and just have a thin left border

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Further testing with  chrome/nvda (after a prod from @ljmaher :) shows this still is not working correctly.

I'm still trying to isolate why it fails, but the markup here is now suffiently simple that it seems to be issues with basic support for `<details>` but hopefully we can get a form that works.

I think this a step in the right direction as its accessibility story _ought_ to be better.   It restores the section headings as real heading markup and  it removes the links from inside the details summary "button" interaction.

I came across this detailed discussion of the issue, it is from 2012 (when html5 and `<details>` were new) .

http://accessibleculture.org/articles/2012/03/screen-readers-and-details-summary/

10 years later things are supposed to work, but if you skip to the end of that page it says this whch is depressingly familiar. So I think not having links in the  summay is a needed first step even if this PR does not fix all the issues.

> **When the summary Begins With a Nested Link**
>
> In JAWS with IE, and in NVDA with both IE and FF, setting focus directly to and activating a summary element whose first bit of content is a nested link will expand or collapse the details element, but at the same time cause that link to fire, which is likely to cause some serious disorientation. While NVDA users can play with the left or right arrow keys to move the Browse Mode cursor to any non-link text within the summary that might exist and then singularly expand/collapse the details element without also activating the nested link, this may not be intuitive. And if the summary contains nothing but a nested link, the user is pretty much out of luck: the nested link will always be fired when trying to expand or collapse the details.

**Comment by davidcarlisle** [comment]
the first version here, keeping `<summary>` but separating it from the header self link has been commited to the main branch as 8306933, we could switch to javascript later but some more experiments with tab index and aria needed.

**Comment by ljmaher** [comment]
Hello David,

Your method works well using Chrome and NVDA, and Firefox, JAWS and NVDA.

It does not work with Chrome and JAWS.

I would declare victory and move on.




Regards
Louis Maher
Phone: 713-444-7838
E-mail: ***@***.***

From: David Carlisle ***@***.***>
Sent: Friday, July 22, 2022 9:34 AM
To: w3c/mathml ***@***.***>
Cc: ljmaher ***@***.***>; Mention ***@***.***>
Subject: [w3c/mathml] folding plan b (PR #405)


Previously folded sections used a html <details><summary> CSS-styled to look like a heading at the appropriate level. Unfortuately because the haeadings have a self-link this resulted in

<details id="abc"><summary><a href="#abc">§</a> title..</summary>



section here...



</details>



And some screen reader configurations could then not separate the open/close interaction on <summary> from the link interaction on <a which is at essentially the same point. And you could get stuck in the lik and not opn (or close or both depding on exactly the variant used)

This PR uses a form that is simpler to generate and makes a more logically clean DOM tree with a real heading and the open/close interaction moved off the headig. So visually it takes up more space, but OK I think, and is (I hope) usable rather than unusable with chrome+nvda and other combinations.

<section>



<h5  id="abc"><a href="#abc">§</a> title..</h5>



<details class="h"><summary class="h"></summary>



section here...



</details>



</section>



the real diff is just the first commit chaging indx.html although I checked in a generated spec.html as well here

@ljmaher<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fljmaher&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187598508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rUe7P%2BFA4ivEaRS6bROg5MGxVU5LF%2FBvYT5EGukwusc%3D&reserved=0> hopefully this works

https://davidcarlisle.github.io/mathml/spec.html#presm_mo_linebreaks<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdavidcarlisle.github.io%2Fmathml%2Fspec.html%23presm_mo_linebreaks&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187598508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jesR83gBarYu3hlMZINcbaey48L5EkGo4mkwobDbEUg%3D&reserved=0>

________________________________

Not totally related but in the current draft open sections in chapter 3 had no special style but open sections in chapter 4 were boxed (which makes it easier to see were the text ends, but is a bit distracting)

Here I have gone for a middle way and just have a thin left border

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/w3c/mathml/pull/405<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187598508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kxns1oBZsh76Zb1OVfdUVpMI%2B%2BQTYy7GJe%2BNJShWw7o%3D&reserved=0>

Commit Summary

  *   adf9770<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Fcommits%2Fadf9770167c04363db6d361c2fba8a42da0bdaaf&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187598508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ynjQf1G4lToQrc0GiwBvY7hRapqFb7GRbjqetIOUKmc%3D&reserved=0> folding plan b
  *   fe19ea9<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Fcommits%2Ffe19ea90f69535857dc9fc9e4455e24c8a49a14b&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZhyI%2BKfVXMa91ri23%2B9kPBFKw7rwYAQn2NdKh9yveIg%3D&reserved=0> generated spec
  *   0a50913<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Fcommits%2F0a5091347e8d36d0bd18b141671b72071c360fba&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wpvvmj7SxAtwnIoR%2FGSWVXEghb%2BLnh%2BoE4qH9z0NWo8%3D&reserved=0> fold test

File Changes

(3 files<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Ffiles&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kdvPxg62x7MK4MdUw1Fj56eYB1oQNUsU7MbE9ThqRgw%3D&reserved=0>)

  *   A fold.html<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Ffiles%23diff-525b5e867e2a83130f66bcbc85c5d48beb0d2b1fdb1d39889638b7dc3d082456&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WN8lsH8%2BoT08yJQ72JJVvr%2BtYuz7UIiTfIzX%2FcB1VWQ%3D&reserved=0> (106)
  *   M index.html<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Ffiles%23diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FlYTC%2B2oSkMH7Dw%2FgtbSL2Je3GF7d4fvBQpb84R8JpM%3D&reserved=0> (54)
  *   A spec.html<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405%2Ffiles%23diff-181371b08d71216599b0acccbaabd03c306da6de142ea6275c2135810999805a&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BXclicAzSWOrB8uVPo7%2BmyP%2FYRxSspBPHnGk0hJQ53c%3D&reserved=0> (49869)

Patch Links:

  *   https://github.com/w3c/mathml/pull/405.patch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405.patch&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8D6rQ%2Bzd6nZI64ZECSssFJae2YGUCA4NftwRcMOe%2FWY%3D&reserved=0>
  *   https://github.com/w3c/mathml/pull/405.diff<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fw3c%2Fmathml%2Fpull%2F405.diff&data=05%7C01%7C%7C71574a7011f842a0d8af08da6bef2996%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637940972187754721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WqiBLxIxgaO6aPax%2F%2FviG7X%2BWbRH%2BCvxEfwVOawK5fE%3D&reserved=0>

-

**Comment by davidcarlisle** [comment]
@ljmaher  thanks for testing. Sounds like it is a lot better than it was, at least.

> It does not work with Chrome and JAWS.

I suggest we try again next year when we are closer to final publication. The system may have improved or internet gossip may still turn up some particular markup incantation that works on this combination without breaking the others.

**Pull request closed without merging**
