### PR TITLE
move from respec-common to respect

### PR DESCRIPTION
**Pull request by airmisdata**

### CODE REVIEW

**Comment by davidcarlisle** [comment]
@airmisdata hi I don't follow respec updates that closely or recall why I used the -common version originally, would it be possible for you to add a comment on the effect of changing version here?

**Comment by airmisdata** [comment]
Sure @davidcarlisle  ! respec-common is now deprecated https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide

**Comment by davidcarlisle** [comment]
@airmisdata  ah thanks that seems clear enough:-)

**Comment by davidcarlisle** [comment]
@airmisdata  I'll do the notes-on mathml (which is currently more or less a copy of this) to match, thanks.

**Pull request merged**
